"""empty message

Revision ID: 64b8f51a0a53
Revises: 0f0c33bb91c7
Create Date: 2020-12-16 00:22:29.254270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b8f51a0a53'
down_revision = '0f0c33bb91c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('publisher', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'publisher')
    # ### end Alembic commands ###
