"""empty message

Revision ID: 70fe5998b4dd
Revises: 120ee2333afe
Create Date: 2021-08-06 13:07:54.982324

"""
from alembic import op
import sqlalchemy as sa


from iatilib import codelists


# revision identifiers, used by Alembic.
revision = '70fe5998b4dd'
down_revision = '120ee2333afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_marker', sa.Column('significance', codelists.PolicySignificance.db_type(), nullable=True))
    op.create_index(op.f('ix_policy_marker_significance'), 'policy_marker', ['significance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_marker_significance'), table_name='policy_marker')
    op.drop_column('policy_marker', 'significance')
    # ### end Alembic commands ###
