"""empty message

Revision ID: f9d3104b97bf
Revises: 64b8f51a0a53
Create Date: 2021-01-08 00:52:31.811724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d3104b97bf'
down_revision = '64b8f51a0a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('label', sa.Unicode(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.execute("INSERT INTO stats (label, count) VALUES ('activities', (SELECT COUNT(*) FROM activity));")
    op.execute("INSERT INTO stats (label, count) VALUES ('transactions', (SELECT COUNT(*) FROM transaction));")
    op.execute("INSERT INTO stats (label, count) VALUES ('budgets', (SELECT COUNT(*) FROM budget));")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
